from typing import Protocol, Self

from sqlalchemy.orm import Session


class UnitOfWork(Protocol):
    @property
    def session(self) -> Session: ...

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
